version: "3.1"
services:
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    command: >
      --requirepass 123456
  splash:
    image: scrapinghub/splash
    ports:
      - "8083:8050"
  haipproxy:
    image: simoon/haipproxy

    ports:
      - "8084:3128"
    depends_on:
      - redis
      - splash