version: "3.1"
services:
  redis:
    image: redis:alpine
    ports:
      - "6381:6379"
    volumes:
      - /F/docker/redis-haipproxy:/data
    command: >
      --requirepass 123456 --appendonly yes

  splash:
    image: scrapinghub/splash
    ports:
      - "8084:8050"
  haipproxy:
    image: daocloud.io/hehe11/haipproxy:latest
    command: sh run.sh
    ports:
      - "8085:3128"
    depends_on:
      - redis
      - splash